apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: openhands-rollout
  namespace: openhands

spec:
  replicas: 2

  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app: openhands

  template:
    metadata:
      labels:
        app: openhands

    spec:
      containers:
        - name: openhands

          image: 360967147235.dkr.ecr.ap-south-1.amazonaws.com/openhands:latest

          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10

  strategy:
    blueGreen:

      activeService: openhands-active

      previewService: openhands-preview

      autoPromotionEnabled: false
